--------------------------------------------------------
--  File created - vasárnap-március-23-2025   
--------------------------------------------------------
DROP TABLE "C##R2KTPS"."ADMIN" cascade constraints;
DROP TABLE "C##R2KTPS"."ALLOMAS" cascade constraints;
DROP TABLE "C##R2KTPS"."JARAT" cascade constraints;
DROP TABLE "C##R2KTPS"."JEGY" cascade constraints;
DROP TABLE "C##R2KTPS"."KEDVEZMENY" cascade constraints;
DROP TABLE "C##R2KTPS"."MEGALL" cascade constraints;
DROP TABLE "C##R2KTPS"."SZERELVENY" cascade constraints;
DROP TABLE "C##R2KTPS"."TAG" cascade constraints;
DROP TABLE "C##R2KTPS"."TULAJDONOS" cascade constraints;
DROP TABLE "C##R2KTPS"."JARAT" cascade constraints;
DROP TABLE "C##R2KTPS"."JEGY" cascade constraints;
DROP TABLE "C##R2KTPS"."ALLOMAS" cascade constraints;
DROP TABLE "C##R2KTPS"."TAG" cascade constraints;
DROP TABLE "C##R2KTPS"."ADMIN" cascade constraints;
DROP TABLE "C##R2KTPS"."KEDVEZMENY" cascade constraints;
DROP TABLE "C##R2KTPS"."MEGALL" cascade constraints;
DROP TABLE "C##R2KTPS"."SZERELVENY" cascade constraints;
DROP TABLE "C##R2KTPS"."TULAJDONOS" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ADMIN" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE), 
	"ADMIN_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ALLOMAS" 
   (	"NEV" VARCHAR2(255 BYTE), 
	"HELY" VARCHAR2(255 BYTE), 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JARAT
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JARAT" 
   (	"JARATSZAM" NUMBER, 
	"ALLOMAS_NEV" VARCHAR2(255 BYTE), 
	"ALLOMAS_HELY" VARCHAR2(255 BYTE), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JEGY" 
   (	"AZONOSITO" NUMBER, 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"VASARLASI_DATUM" DATE, 
	"ERVENYESSEG" DATE, 
	"JEGYAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEDVEZMENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."KEDVEZMENY" 
   (	"ID" NUMBER, 
	"JEGY_AZONOSITO" NUMBER, 
	"ELNEVEZES" VARCHAR2(255 BYTE), 
	"TIPUS" VARCHAR2(255 BYTE), 
	"MERTEKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALL
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."MEGALL" 
   (	"JARAT_JARATSZAM" NUMBER(8,0), 
	"ALLOMAS_NEV" VARCHAR2(255 BYTE), 
	"ALLOMAS_HELY" VARCHAR2(255 BYTE), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."SZERELVENY" 
   (	"MOZDONYAZAM" NUMBER(8,0), 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"KAPACITAS" NUMBER, 
	"TIPUS" VARCHAR2(255 BYTE), 
	"ALLAPOT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."TAG" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TULAJDONOS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."TULAJDONOS" 
   (	"TAG_EMAIL" VARCHAR2(255 BYTE), 
	"JEGY_AZONOSITO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JARAT
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JARAT" 
   (	"JARATSZAM" NUMBER, 
	"ALLOMAS_NEV" VARCHAR2(255 BYTE), 
	"ALLOMAS_HELY" VARCHAR2(255 BYTE), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JEGY" 
   (	"AZONOSITO" NUMBER, 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"VASARLASI_DATUM" DATE, 
	"ERVENYESSEG" DATE, 
	"JEGYAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ALLOMAS" 
   (	"NEV" VARCHAR2(255 BYTE), 
	"HELY" VARCHAR2(255 BYTE), 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."TAG" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ADMIN" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE), 
	"ADMIN_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEDVEZMENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."KEDVEZMENY" 
   (	"ID" NUMBER, 
	"JEGY_AZONOSITO" NUMBER, 
	"ELNEVEZES" VARCHAR2(255 BYTE), 
	"TIPUS" VARCHAR2(255 BYTE), 
	"MERTEKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALL
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."MEGALL" 
   (	"JARAT_JARATSZAM" NUMBER(8,0), 
	"ALLOMAS_NEV" VARCHAR2(255 BYTE), 
	"ALLOMAS_HELY" VARCHAR2(255 BYTE), 
	"MIKOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."SZERELVENY" 
   (	"MOZDONYAZAM" NUMBER(8,0), 
	"JARAT_JARATSZAM" NUMBER(8,0), 
	"KAPACITAS" NUMBER, 
	"TIPUS" VARCHAR2(255 BYTE), 
	"ALLAPOT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TULAJDONOS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."TULAJDONOS" 
   (	"TAG_EMAIL" VARCHAR2(255 BYTE), 
	"JEGY_AZONOSITO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##R2KTPS.ADMIN
SET DEFINE OFF;
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin1@vasut.hu','SzuperTitkosJelszo001!','Adminisztrátor Első','1');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin2@vasut.hu','SzuperTitkosJelszo002!','Adminisztrátor Második','2');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin3@vasut.hu','Asdasdasd1!','Adminisztrátor Harmadik','3');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin4@vasut.hu','SzuperTitkosJelszo001@','Adminisztrátor Negyedik','4');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin5@vasut.hu','AdminJelszo1235!','Adminisztrátor Ötödik','5');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin6@vasut.hu','SzuperTitkosJelszo22!','Adminisztrátor Hatodik','6');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin7@vasut.hu','SzuperTitkosJelszo001!','Adminisztrátor Hetedik','7');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin8@vasut.hu','S+Z362V08888888','Adminisztrátor Nyolcadik','8');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin9@vasut.hu','Szia999999!V','Adminisztrátor Kilencedik','9');
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin10@vasut.hu','Ferencvaros222VT!','Adminisztrátor Tizedik','10');
REM INSERTING into C##R2KTPS.ALLOMAS
SET DEFINE OFF;
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Budapest-Keleti','Budapest','10000001',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Debrecen Főpályaudvar','Debrecen','10000002',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Szeged Állomás','Szeged','10000003',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Pécs Főpályaudvar','Pécs','10000004',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Győr Állomás','Győr','10000005',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Miskolc-Tiszai','Miskolc','10000006',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Nyíregyháza Állomás','Nyíregyháza','10000007',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Szombathely Állomás','Szombathely','10000008',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Békéscsaba Állomás','Békéscsaba','10000009',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.ALLOMAS (NEV,HELY,JARAT_JARATSZAM,MIKOR) values ('Kecskemét Állomás','Kecskemét','10000010',to_date('25-ÁPR.  -01','RR-MON-DD'));
REM INSERTING into C##R2KTPS.JARAT
SET DEFINE OFF;
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000001','Budapest','Budapest-Keleti',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000002','Debrecen','Debrecen Főpályaudvar',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000003','Szeged','Szeged Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000004','Pécs','Pécs Főpályaudvar',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000005','Győr','Győr Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000006','Miskolc','Miskolc-Tiszai',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000007','Nyíregyháza','Nyíregyháza Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000008','Szombathely','Szombathely Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000009','Békéscsaba','Békéscsaba Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.JARAT (JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000010','Kecskemét','Kecskemét Állomás',to_date('25-ÁPR.  -01','RR-MON-DD'));
REM INSERTING into C##R2KTPS.JEGY
SET DEFINE OFF;
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('1','10000001',to_date('25-MÁRC. -15','RR-MON-DD'),to_date('25-MÁRC. -15','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('2','10000002',to_date('25-MÁRC. -16','RR-MON-DD'),to_date('25-MÁRC. -16','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('3','10000003',to_date('25-MÁRC. -17','RR-MON-DD'),to_date('25-MÁRC. -17','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('4','10000004',to_date('25-MÁRC. -18','RR-MON-DD'),to_date('25-MÁRC. -18','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('5','10000005',to_date('25-MÁRC. -19','RR-MON-DD'),to_date('25-MÁRC. -19','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('6','10000006',to_date('25-MÁRC. -20','RR-MON-DD'),to_date('25-MÁRC. -20','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('7','10000007',to_date('25-MÁRC. -21','RR-MON-DD'),to_date('25-MÁRC. -21','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('8','10000008',to_date('25-MÁRC. -22','RR-MON-DD'),to_date('25-MÁRC. -22','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('9','10000009',to_date('25-MÁRC. -23','RR-MON-DD'),to_date('25-MÁRC. -23','RR-MON-DD'),'1500');
Insert into C##R2KTPS.JEGY (AZONOSITO,JARAT_JARATSZAM,VASARLASI_DATUM,ERVENYESSEG,JEGYAR) values ('10','10000010',to_date('25-MÁRC. -24','RR-MON-DD'),to_date('25-MÁRC. -24','RR-MON-DD'),'1500');
REM INSERTING into C##R2KTPS.KEDVEZMENY
SET DEFINE OFF;
Insert into C##R2KTPS.KEDVEZMENY (ID,JEGY_AZONOSITO,ELNEVEZES,TIPUS,MERTEKE) values ('1','1','Diákkedvezmény','Tanulói','50');
Insert into C##R2KTPS.KEDVEZMENY (ID,JEGY_AZONOSITO,ELNEVEZES,TIPUS,MERTEKE) values ('2','2','Nyugdíjas kedvezmény','Nyugdíjas','50');
Insert into C##R2KTPS.KEDVEZMENY (ID,JEGY_AZONOSITO,ELNEVEZES,TIPUS,MERTEKE) values ('3','3','Családi kedvezmény','Családi','33');
Insert into C##R2KTPS.KEDVEZMENY (ID,JEGY_AZONOSITO,ELNEVEZES,TIPUS,MERTEKE) values ('4','4','Csoportos kedvezmény','Csoport','25');
Insert into C##R2KTPS.KEDVEZMENY (ID,JEGY_AZONOSITO,ELNEVEZES,TIPUS,MERTEKE) values ('5','5','Fogyatékkal élők kedvezménye','Egyéb','90');
REM INSERTING into C##R2KTPS.MEGALL
SET DEFINE OFF;
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000001','Budapest-Keleti','Budapest',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000002','Debrecen Főpályaudvar','Debrecen',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000003','Szeged Állomás','Szeged',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000004','Pécs Főpályaudvar','Pécs',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000005','Győr Állomás','Győr',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000006','Miskolc-Tiszai','Miskolc',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000007','Nyíregyháza Állomás','Nyíregyháza',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000008','Szombathely Állomás','Szombathely',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000009','Békéscsaba Állomás','Békéscsaba',to_date('25-ÁPR.  -01','RR-MON-DD'));
Insert into C##R2KTPS.MEGALL (JARAT_JARATSZAM,ALLOMAS_NEV,ALLOMAS_HELY,MIKOR) values ('10000010','Kecskemét Állomás','Kecskemét',to_date('25-ÁPR.  -01','RR-MON-DD'));
REM INSERTING into C##R2KTPS.SZERELVENY
SET DEFINE OFF;
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000001','10000001','120','IC','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000002','10000002','150','EC','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000003','10000003','100','Sebes','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000004','10000004','130','IC','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000005','10000005','140','EC','Karbantartás alatt');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000006','10000006','110','Sebes','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000007','10000007','125','IC','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000008','10000008','135','Gyors','Üzemképes');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000009','10000009','115','Sebes','Karbantartás alatt');
Insert into C##R2KTPS.SZERELVENY (MOZDONYAZAM,JARAT_JARATSZAM,KAPACITAS,TIPUS,ALLAPOT) values ('50000010','10000010','145','EC','Üzemképes');
REM INSERTING into C##R2KTPS.TAG
SET DEFINE OFF;
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('kiss.janos@gmail.com','SzuperTitkosJelszo001!','Kiss János');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('nagy.eva@gmail.com','SzuperTitkosJelszo002!','Nagy Éva');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('szabo.peter@gmail.com','SzuperTitkosJelszo003!','Szabó Péter');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('kovacs.anna@gmail.com','SzuperTitkosJelszo004!','Kovács Anna');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('toth.istvan@gmail.com','SzuperTitkosJelszo005!','Tóth István');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('horvath.maria@gmail.com','SzuperTitkosJelszo006!','Horváth Mária');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('fekete.zoltan@gmail.com','SzuperTitkosJelszo007!','Fekete Zoltán');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('varga.katalin@gmail.com','SzuperTitkosJelszo008!','Varga Katalin');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('balogh.gabor@gmail.com','SzuperTitkosJelszo009!','Balogh Gábor');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('nemet.judit@gmail.com','SzuperTitkosJelszo010!','Német Judit');
REM INSERTING into C##R2KTPS.TULAJDONOS
SET DEFINE OFF;
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('balogh.gabor@gmail.com','9');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('fekete.zoltan@gmail.com','7');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('horvath.maria@gmail.com','6');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('kiss.janos@gmail.com','1');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('kiss.janos@gmail.com','2');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('kovacs.anna@gmail.com','4');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('nemet.judit@gmail.com','10');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('szabo.peter@gmail.com','3');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('toth.istvan@gmail.com','5');
Insert into C##R2KTPS.TULAJDONOS (TAG_EMAIL,JEGY_AZONOSITO) values ('varga.katalin@gmail.com','8');
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."ADMIN_PK" ON "C##R2KTPS"."ADMIN" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."ALLOMAS_PK" ON "C##R2KTPS"."ALLOMAS" ("NEV", "HELY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JARAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."JARAT_PK" ON "C##R2KTPS"."JARAT" ("JARATSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JEGY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."JEGY_PK" ON "C##R2KTPS"."JEGY" ("AZONOSITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KEDVEZMENY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."KEDVEZMENY_PK" ON "C##R2KTPS"."KEDVEZMENY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEGALL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."MEGALL_PK" ON "C##R2KTPS"."MEGALL" ("JARAT_JARATSZAM", "ALLOMAS_NEV", "ALLOMAS_HELY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."SZERELVENY_PK" ON "C##R2KTPS"."SZERELVENY" ("MOZDONYAZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."TAG_PK" ON "C##R2KTPS"."TAG" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TULAJDONOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."TULAJDONOS_PK" ON "C##R2KTPS"."TULAJDONOS" ("TAG_EMAIL", "JEGY_AZONOSITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."ALLOMAS" ADD CONSTRAINT "ALLOMAS_PK" PRIMARY KEY ("NEV", "HELY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("HELY" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("MIKOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JARAT
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JARAT" ADD CONSTRAINT "JARAT_PK" PRIMARY KEY ("JARATSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."JARAT" MODIFY ("ALLOMAS_NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JARAT" MODIFY ("ALLOMAS_HELY" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JARAT" MODIFY ("MIKOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_PK" PRIMARY KEY ("AZONOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("AZONOSITO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("VASARLASI_DATUM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("ERVENYESSEG" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("JEGYAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KEDVEZMENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" ADD CONSTRAINT "KEDVEZMENY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("JEGY_AZONOSITO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("ELNEVEZES" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("MERTEKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEGALL
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."MEGALL" ADD CONSTRAINT "MEGALL_PK" PRIMARY KEY ("JARAT_JARATSZAM", "ALLOMAS_NEV", "ALLOMAS_HELY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("ALLOMAS_NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("ALLOMAS_HELY" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("MIKOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("MOZDONYAZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("KAPACITAS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("ALLAPOT" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" ADD CONSTRAINT "SZERELVENY_PK" PRIMARY KEY ("MOZDONYAZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TULAJDONOS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."TULAJDONOS" MODIFY ("TAG_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TULAJDONOS" MODIFY ("JEGY_AZONOSITO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TULAJDONOS" ADD CONSTRAINT "TULAJDONOS_PK" PRIMARY KEY ("TAG_EMAIL", "JEGY_AZONOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."ALLOMAS" ADD CONSTRAINT "ALLOMAS_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##R2KTPS"."JARAT" ("JARATSZAM") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##R2KTPS"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KEDVEZMENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" ADD CONSTRAINT "KEDVEZMENY_FK_JEGY" FOREIGN KEY ("JEGY_AZONOSITO")
	  REFERENCES "C##R2KTPS"."JEGY" ("AZONOSITO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEGALL
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."MEGALL" ADD CONSTRAINT "MEGALL_FK_ALLOMAS" FOREIGN KEY ("ALLOMAS_NEV", "ALLOMAS_HELY")
	  REFERENCES "C##R2KTPS"."ALLOMAS" ("NEV", "HELY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##R2KTPS"."MEGALL" ADD CONSTRAINT "MEGALL_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##R2KTPS"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."SZERELVENY" ADD CONSTRAINT "SZERELVENY_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##R2KTPS"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TULAJDONOS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."TULAJDONOS" ADD CONSTRAINT "TULAJDONOS_FK_JEGY" FOREIGN KEY ("JEGY_AZONOSITO")
	  REFERENCES "C##R2KTPS"."JEGY" ("AZONOSITO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##R2KTPS"."TULAJDONOS" ADD CONSTRAINT "TULAJDONOS_FK_TAG" FOREIGN KEY ("TAG_EMAIL")
	  REFERENCES "C##R2KTPS"."TAG" ("EMAIL") ON DELETE CASCADE ENABLE;
