--------------------------------------------------------
--  File created - vasárnap-április-27-2025   
--------------------------------------------------------
DROP TABLE "C##ALONKX"."ADMIN" cascade constraints;
DROP TABLE "C##ALONKX"."ALLOMAS" cascade constraints;
DROP TABLE "C##ALONKX"."JARAT" cascade constraints;
DROP TABLE "C##ALONKX"."JEGY" cascade constraints;
DROP TABLE "C##ALONKX"."KEDVEZMENY" cascade constraints;
DROP TABLE "C##ALONKX"."MEGALL" cascade constraints;
DROP TABLE "C##ALONKX"."SZERELVENY" cascade constraints;
DROP TABLE "C##ALONKX"."TAG" cascade constraints;
DROP TABLE "C##ALONKX"."VASARLAS" cascade constraints;
DROP TABLE "C##ALONKX"."SZERELVENY" cascade constraints;
DROP TABLE "C##ALONKX"."JARAT" cascade constraints;
DROP TABLE "C##ALONKX"."KEDVEZMENY" cascade constraints;
DROP TABLE "C##ALONKX"."TAG" cascade constraints;
DROP TABLE "C##ALONKX"."VASARLAS" cascade constraints;
DROP TABLE "C##ALONKX"."ALLOMAS" cascade constraints;
DROP TABLE "C##ALONKX"."ADMIN" cascade constraints;
DROP TABLE "C##ALONKX"."JEGY" cascade constraints;
DROP TABLE "C##ALONKX"."MEGALL" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ALONKX"."ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ALLOMAS_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##ALONKX"."ALLOMAS_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JARAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ALONKX"."JARAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KEDVEZMENY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ALONKX"."KEDVEZMENY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MEGALL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ALONKX"."MEGALL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."ADMIN" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE), 
	"ADMIN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."ALLOMAS" 
   (	"ID" NUMBER(*,0), 
	"NEV" VARCHAR2(255 BYTE), 
	"HELY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JARAT
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."JARAT" 
   (	"JARATSZAM" NUMBER(*,0), 
	"TIPUS" VARCHAR2(255 BYTE), 
	"SZERELVENY_MOZDONYSZAM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."JEGY" 
   (	"AZONOSITO" NUMBER(*,0), 
	"JARAT_JARATSZAM" NUMBER(*,0), 
	"VASARLAS_ID" NUMBER(*,0), 
	"ERVENYESSEG" DATE, 
	"JEGYAR" NUMBER, 
	"KEDVEZMENYEK_ID" NUMBER, 
	"TAG_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEDVEZMENY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."KEDVEZMENY" 
   (	"ID" NUMBER, 
	"TIPUS" VARCHAR2(255 BYTE), 
	"MERTEKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALL
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."MEGALL" 
   (	"ID" NUMBER, 
	"JARAT_JARATSZAM" NUMBER, 
	"ALLOMAS_ID" NUMBER, 
	"INDULAS" DATE, 
	"ERKEZES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."SZERELVENY" 
   (	"MOZDONYSZAM" NUMBER(*,0), 
	"KAPACITAS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."TAG" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VASARLAS
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."VASARLAS" 
   (	"ID" NUMBER, 
	"DATUM" DATE, 
	"FIZETESI_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."SZERELVENY" 
   (	"MOZDONYSZAM" NUMBER(*,0), 
	"KAPACITAS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JARAT
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."JARAT" 
   (	"JARATSZAM" NUMBER(*,0), 
	"TIPUS" VARCHAR2(255 BYTE), 
	"SZERELVENY_MOZDONYSZAM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEDVEZMENY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."KEDVEZMENY" 
   (	"ID" NUMBER, 
	"TIPUS" VARCHAR2(255 BYTE), 
	"MERTEKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."TAG" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VASARLAS
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."VASARLAS" 
   (	"ID" NUMBER, 
	"DATUM" DATE, 
	"FIZETESI_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."ALLOMAS" 
   (	"ID" NUMBER(*,0), 
	"NEV" VARCHAR2(255 BYTE), 
	"HELY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."ADMIN" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE), 
	"ADMIN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."JEGY" 
   (	"AZONOSITO" NUMBER(*,0), 
	"JARAT_JARATSZAM" NUMBER(*,0), 
	"VASARLAS_ID" NUMBER(*,0), 
	"ERVENYESSEG" DATE, 
	"JEGYAR" NUMBER, 
	"KEDVEZMENYEK_ID" NUMBER, 
	"TAG_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALL
--------------------------------------------------------

  CREATE TABLE "C##ALONKX"."MEGALL" 
   (	"ID" NUMBER, 
	"JARAT_JARATSZAM" NUMBER, 
	"ALLOMAS_ID" NUMBER, 
	"INDULAS" DATE, 
	"ERKEZES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ALONKX.ADMIN
SET DEFINE OFF;
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin1@vasut.hu','$2y$10$vHfsxF5UPoSRlQO8YJa6f.NVfV8LSEyQqVRce.Fypl51WkaDZFBfG','Adminisztrátor Első','1');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin2@vasut.hu','SzuperTitkosJelszo002!','Adminisztrátor Második','2');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin3@vasut.hu','Asdasdasd1!','Adminisztrátor Harmadik','3');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin4@vasut.hu','SzuperTitkosJelszo001@','Adminisztrátor Negyedik','4');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin5@vasut.hu','AdminJelszo1235!','Adminisztrátor Ötödik','5');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin6@vasut.hu','SzuperTitkosJelszo22!','Adminisztrátor Hatodik','6');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin7@vasut.hu','SzuperTitkosJelszo001!','Adminisztrátor Hetedik','7');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin8@vasut.hu','S+Z362V08888888','Adminisztrátor Nyolcadik','8');
Insert into C##ALONKX.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('fradista@vasut.hu','Ferencvaros222VT!','Hajrá Ferencváros!','10');
REM INSERTING into C##ALONKX.ALLOMAS
SET DEFINE OFF;
Insert into C##ALONKX.ALLOMAS (ID,NEV,HELY) values ('1','Sarkadi Cukorgyár','Sarkad');
Insert into C##ALONKX.ALLOMAS (ID,NEV,HELY) values ('2','Gyulai Városerdő','Gyula');
REM INSERTING into C##ALONKX.JARAT
SET DEFINE OFF;
Insert into C##ALONKX.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values ('2','Szemely','222222');
REM INSERTING into C##ALONKX.JEGY
SET DEFINE OFF;
REM INSERTING into C##ALONKX.KEDVEZMENY
SET DEFINE OFF;
Insert into C##ALONKX.KEDVEZMENY (ID,TIPUS,MERTEKE) values ('1','Diákkedvezmény','50');
REM INSERTING into C##ALONKX.MEGALL
SET DEFINE OFF;
REM INSERTING into C##ALONKX.SZERELVENY
SET DEFINE OFF;
Insert into C##ALONKX.SZERELVENY (MOZDONYSZAM,KAPACITAS) values ('222222','200');
Insert into C##ALONKX.SZERELVENY (MOZDONYSZAM,KAPACITAS) values ('111111','1000');
REM INSERTING into C##ALONKX.TAG
SET DEFINE OFF;
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('kiss.janos@gmail.com','SzuperTitkosJelszo001!','Kiss János');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('nagy.eva@gmail.com','SzuperTitkosJelszo002!','Nagy Éva');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('szabo.peter@gmail.com','SzuperTitkosJelszo003!','Szabó Péter');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('kovacs.anna@gmail.com','SzuperTitkosJelszo004!','Kovács Anna');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('toth.istvan@gmail.com','SzuperTitkosJelszo005!','Tóth István');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('horvath.maria@gmail.com','SzuperTitkosJelszo006!','Horváth Mária');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('varga.katalin@gmail.com','SzuperTitkosJelszo008!','Varga Katalin');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('balogh.gabor@gmail.com','SzuperTitkosJelszo009!','Balogh Gábor');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('nemet.judit@gmail.com','SzuperTitkosJelszo010!','Német Judit');
Insert into C##ALONKX.TAG (EMAIL,JELSZO,NEV) values ('ez','$2y$10$F5ArhSE7nUMwALNKOvSsz.WopqN1UPOlqJRAWz0Vd1h4aHc3iltny','az');
REM INSERTING into C##ALONKX.VASARLAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."ADMIN_PK" ON "C##ALONKX"."ADMIN" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."ALLOMAS_PK" ON "C##ALONKX"."ALLOMAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JARAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."JARAT_PK" ON "C##ALONKX"."JARAT" ("JARATSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JEGY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."JEGY_PK" ON "C##ALONKX"."JEGY" ("AZONOSITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KEDVEZMENY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."KEDVEZMENY_PK" ON "C##ALONKX"."KEDVEZMENY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEGALL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."MEGALL_PK" ON "C##ALONKX"."MEGALL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."SZERELVENY_PK" ON "C##ALONKX"."SZERELVENY" ("MOZDONYSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."TAG_PK" ON "C##ALONKX"."TAG" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VASARLAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ALONKX"."VASARLAS_PK" ON "C##ALONKX"."VASARLAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADMIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."ADMIN_TRG" 
BEFORE INSERT ON ADMIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMIN_ID IS NULL THEN
      SELECT ADMIN_SEQ.NEXTVAL INTO :NEW.ADMIN_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."ADMIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."ALLOMAS_TRG2" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ALLOMAS_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."ALLOMAS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."ALLOMAS_TRG" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."ALLOMAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."ALLOMAS_TRG1" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."ALLOMAS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JARAT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."JARAT_TRG" 
BEFORE INSERT ON JARAT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.JARATSZAM IS NULL THEN
      SELECT JARAT_SEQ.NEXTVAL INTO :NEW.JARATSZAM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."JARAT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JEGY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."JEGY_TRG" 
BEFORE INSERT ON JEGY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."JEGY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KEDVEZMENY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."KEDVEZMENY_TRG" 
BEFORE INSERT ON KEDVEZMENY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT KEDVEZMENY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."KEDVEZMENY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEGALL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."MEGALL_TRG" 
BEFORE INSERT ON MEGALL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MEGALL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."MEGALL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SZERELVENY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ALONKX"."SZERELVENY_TRG" 
BEFORE INSERT ON SZERELVENY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ALONKX"."SZERELVENY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."ADMIN" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."ADMIN" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."ALLOMAS" ADD CONSTRAINT "ALLOMAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."ALLOMAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."ALLOMAS" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."ALLOMAS" MODIFY ("HELY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JARAT
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."JARAT" ADD CONSTRAINT "JARAT_PK" PRIMARY KEY ("JARATSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."JARAT" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JARAT" MODIFY ("SZERELVENY_MOZDONYSZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."JEGY" ADD CONSTRAINT "JEGY_PK" PRIMARY KEY ("AZONOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("AZONOSITO" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("VASARLAS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("ERVENYESSEG" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("JEGYAR" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("KEDVEZMENYEK_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."JEGY" MODIFY ("TAG_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KEDVEZMENY
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."KEDVEZMENY" ADD CONSTRAINT "KEDVEZMENY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."KEDVEZMENY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."KEDVEZMENY" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."KEDVEZMENY" MODIFY ("MERTEKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEGALL
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."MEGALL" ADD CONSTRAINT "MEGALL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ALONKX"."MEGALL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."MEGALL" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."MEGALL" MODIFY ("ALLOMAS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."SZERELVENY" MODIFY ("MOZDONYSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."SZERELVENY" MODIFY ("KAPACITAS" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."SZERELVENY" ADD CONSTRAINT "SZERELVENY_PK" PRIMARY KEY ("MOZDONYSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."TAG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."TAG" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."TAG" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VASARLAS
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."VASARLAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."VASARLAS" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."VASARLAS" MODIFY ("FIZETESI_MOD" NOT NULL ENABLE);
  ALTER TABLE "C##ALONKX"."VASARLAS" ADD CONSTRAINT "VASARLAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JARAT
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."JARAT" ADD CONSTRAINT "JARAT_FK_MOZDONYSZAM" FOREIGN KEY ("SZERELVENY_MOZDONYSZAM")
	  REFERENCES "C##ALONKX"."SZERELVENY" ("MOZDONYSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."JEGY" ADD CONSTRAINT "JEGY_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##ALONKX"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ALONKX"."JEGY" ADD CONSTRAINT "JEGY_FK_KEDVEZMENY" FOREIGN KEY ("KEDVEZMENYEK_ID")
	  REFERENCES "C##ALONKX"."KEDVEZMENY" ("ID") ENABLE;
  ALTER TABLE "C##ALONKX"."JEGY" ADD CONSTRAINT "JEGY_FK_TAG_EMAIL" FOREIGN KEY ("TAG_EMAIL")
	  REFERENCES "C##ALONKX"."TAG" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ALONKX"."JEGY" ADD CONSTRAINT "JEGY_FK_VASARLAS" FOREIGN KEY ("AZONOSITO")
	  REFERENCES "C##ALONKX"."VASARLAS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEGALL
--------------------------------------------------------

  ALTER TABLE "C##ALONKX"."MEGALL" ADD CONSTRAINT "MEGALL_FK_ALLOMAS" FOREIGN KEY ("ALLOMAS_ID")
	  REFERENCES "C##ALONKX"."ALLOMAS" ("ID") ENABLE;
  ALTER TABLE "C##ALONKX"."MEGALL" ADD CONSTRAINT "MEGALL_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##ALONKX"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
