--------------------------------------------------------
--  File created - szerda-május-14-2025   
--------------------------------------------------------
DROP SEQUENCE "C##R2KTPS"."ADMIN_SEQ";
DROP SEQUENCE "C##R2KTPS"."ALLOMAS_SEQ2";
DROP SEQUENCE "C##R2KTPS"."JARAT_SEQ";
DROP SEQUENCE "C##R2KTPS"."KEDVEZMENY_SEQ";
DROP SEQUENCE "C##R2KTPS"."MEGALL_SEQ";
DROP TABLE "C##R2KTPS"."ADMIN" cascade constraints;
DROP TABLE "C##R2KTPS"."ALLOMAS" cascade constraints;
DROP TABLE "C##R2KTPS"."JARAT" cascade constraints;
DROP TABLE "C##R2KTPS"."JEGY" cascade constraints;
DROP TABLE "C##R2KTPS"."KEDVEZMENY" cascade constraints;
DROP TABLE "C##R2KTPS"."MEGALL" cascade constraints;
DROP TABLE "C##R2KTPS"."SZERELVENY" cascade constraints;
DROP TABLE "C##R2KTPS"."TAG" cascade constraints;
DROP TABLE "C##R2KTPS"."VASARLAS" cascade constraints;
DROP PROCEDURE "C##R2KTPS"."ADD_TAG";
DROP PROCEDURE "C##R2KTPS"."GET_NEXT_VASARLAS_ID";
DROP PROCEDURE "C##R2KTPS"."SZEMELY_KKIR";
--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##R2KTPS"."ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ALLOMAS_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##R2KTPS"."ALLOMAS_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JARAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##R2KTPS"."JARAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KEDVEZMENY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##R2KTPS"."KEDVEZMENY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MEGALL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##R2KTPS"."MEGALL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ADMIN" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE), 
	"ADMIN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."ALLOMAS" 
   (	"ID" NUMBER(*,0), 
	"NEV" VARCHAR2(255 BYTE), 
	"HELY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JARAT
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JARAT" 
   (	"JARATSZAM" NUMBER(*,0), 
	"TIPUS" VARCHAR2(255 BYTE), 
	"SZERELVENY_MOZDONYSZAM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."JEGY" 
   (	"AZONOSITO" NUMBER(*,0), 
	"JARAT_JARATSZAM" NUMBER(*,0), 
	"VASARLAS_ID" NUMBER(*,0), 
	"ERVENYESSEG" DATE, 
	"JEGYAR" NUMBER, 
	"KEDVEZMENYEK_ID" NUMBER, 
	"TAG_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEDVEZMENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."KEDVEZMENY" 
   (	"ID" NUMBER, 
	"TIPUS" VARCHAR2(255 BYTE), 
	"MERTEKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALL
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."MEGALL" 
   (	"ID" NUMBER, 
	"JARAT_JARATSZAM" NUMBER, 
	"ALLOMAS_ID" NUMBER, 
	"INDULAS" DATE, 
	"ERKEZES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."SZERELVENY" 
   (	"MOZDONYSZAM" NUMBER(*,0), 
	"KAPACITAS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."TAG" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"JELSZO" VARCHAR2(255 BYTE), 
	"NEV" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VASARLAS
--------------------------------------------------------

  CREATE TABLE "C##R2KTPS"."VASARLAS" 
   (	"ID" NUMBER, 
	"DATUM" DATE, 
	"FIZETESI_MOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##R2KTPS.ADMIN
SET DEFINE OFF;
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin1@vasut.hu','$2y$10$vHfsxF5UPoSRlQO8YJa6f.NVfV8LSEyQqVRce.Fypl51WkaDZFBfG','Adminisztrátor Első',1);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin3@vasut.hu','Asdasdasd1!','Adminisztrátor Harmadik',3);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin4@vasut.hu','SzuperTitkosJelszo001@','Adminisztrátor Negyedik',4);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin5@vasut.hu','AdminJelszo1235!','Adminisztrátor Ötödik',5);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin6@vasut.hu','SzuperTitkosJelszo22!','Adminisztrátor Hatodik',6);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin7@vasut.hu','SzuperTitkosJelszo001!','Adminisztrátor Hetedik',7);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('admin8@vasut.hu','S+Z362V08888888','Adminisztrátor Nyolcadik',8);
Insert into C##R2KTPS.ADMIN (EMAIL,JELSZO,NEV,ADMIN_ID) values ('fradista@vasut.hu','Ferencvaros222VT!','Hajrá Ferencváros!',10);
REM INSERTING into C##R2KTPS.ALLOMAS
SET DEFINE OFF;
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (1,'Sarkadi Cukorgyár','Sarkad');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (4,'Szeged-Rókus','Szeged');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (2,'Szeged-Tarján','Szeged');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (3,'Budapest-Nagykörút','Budapest');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (5,'Algyő-kereszteződés','Algyő');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (6,'Szeged-Vértó','Szeged');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (7,'Szeged-Gumigyár','Szeged');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (8,'Szarvas-aut. áll.','Szarvas');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (9,'Orosháza-aut. áll.','Orosháza');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (11,'Baja-aut. áll.','Baja');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (12,'Szeged-Észak','Szeged');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (13,'Békéscsaba-Belváros','Békéscsaba');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (14,'Hódmezővásárhely-Központ','Hódmezővásárhely');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (15,'Kecskemét-Főtér','Kecskemét');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (16,'Makó-Buszpályaudvar','Makó');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (17,'Kalocsa-aut. áll.','Kalocsa');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (18,'Szolnok-Külső','Szolnok');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (19,'Kiskunhalas-Központ','Kiskunhalas');
Insert into C##R2KTPS.ALLOMAS (ID,NEV,HELY) values (20,'Csongrád-Busztér','Csongrád');
REM INSERTING into C##R2KTPS.JARAT
SET DEFINE OFF;
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (111111,'Interregio',333333);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1001,'Szemely',111111);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1002,'RE',444444);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1003,'Személyvonat',444444);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1004,'Gyorsvonat',444444);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1005,'IC',444444);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1006,'Gyorsvonat',30000);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1007,'Személyvonat',111111);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1009,'IC',111111);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1010,'RE',222222);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1011,'Személyvonat',222222);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1012,'Gyorsvonat',222222);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1013,'IC',222222);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1014,'RE',333333);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1015,'IC',444444);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1016,'RE',555555);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1017,'SE',666666);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1018,'EX',777777);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1019,'IC',888888);
Insert into C##R2KTPS.JARAT (JARATSZAM,TIPUS,SZERELVENY_MOZDONYSZAM) values (1020,'RE',999999);
REM INSERTING into C##R2KTPS.JEGY
SET DEFINE OFF;
REM INSERTING into C##R2KTPS.KEDVEZMENY
SET DEFINE OFF;
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (1,'Diákkedvezmény',50);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (2,'Nyugdíjas',30);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (3,'Családi',20);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (4,'Helyi kedvezmény',15);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (5,'Hűséges utas',10);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (6,'Korai foglalás',25);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (7,'Csoportos',35);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (8,'Fogyatékos',60);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (9,'Kisgyermekes',40);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (10,'Vasutas',70);
Insert into C##R2KTPS.KEDVEZMENY (ID,TIPUS,MERTEKE) values (1,'Diákkedvezmény',50);
REM INSERTING into C##R2KTPS.MEGALL
SET DEFINE OFF;
INSERT INTO C##R2KTPS.MEGALL VALUES (1, 1001, 1, TO_DATE('05-MAY-25 08:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (2, 1001, 2, TO_DATE('05-MAY-25 08:35:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (3, 1001, 3, TO_DATE('05-MAY-25 09:10:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (4, 1002, 3, TO_DATE('05-MAY-25 09:45:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (5, 1002, 4, TO_DATE('05-MAY-25 10:05:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (6, 1002, 5, TO_DATE('05-MAY-25 10:35:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (7, 1003, 5, TO_DATE('05-MAY-25 11:10:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (8, 1003, 6, TO_DATE('05-MAY-25 11:35:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (9, 1003, 7, TO_DATE('05-MAY-25 12:05:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (10, 1004, 7, TO_DATE('05-MAY-25 12:35:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (11, 1004, 8, TO_DATE('05-MAY-25 13:05:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (12, 1004, 9, TO_DATE('05-MAY-25 13:35:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (13, 1005, 2, TO_DATE('05-MAY-25 09:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (14, 1005, 6, TO_DATE('05-MAY-25 09:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (15, 1005, 10, TO_DATE('05-MAY-25 10:10:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:40:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (16, 1006, 4, TO_DATE('05-MAY-25 10:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (17, 1006, 7, TO_DATE('05-MAY-25 10:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (18, 1006, 10, TO_DATE('05-MAY-25 11:05:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:30:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (19, 1007, 1, TO_DATE('05-MAY-25 08:15:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:40:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (20, 1007, 6, TO_DATE('05-MAY-25 08:45:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:10:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (21, 1007, 8, TO_DATE('05-MAY-25 09:15:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:40:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (22, 1008, 9, TO_DATE('05-MAY-25 13:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:20:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (23, 1008, 10, TO_DATE('05-MAY-25 13:25:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:50:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (24, 1008, 3, TO_DATE('05-MAY-25 13:55:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:20:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (25, 1009, 2, TO_DATE('05-MAY-25 07:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 07:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (26, 1009, 5, TO_DATE('05-MAY-25 07:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (27, 1009, 8, TO_DATE('05-MAY-25 08:05:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:35:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (28, 1010, 4, TO_DATE('05-MAY-25 12:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:20:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (29, 1010, 6, TO_DATE('05-MAY-25 12:25:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:50:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (30, 1010, 9, TO_DATE('05-MAY-25 12:55:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:20:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (31, 1003, 1, TO_DATE('05-MAY-25 10:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (32, 1003, 4, TO_DATE('05-MAY-25 10:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (33, 1003, 8, TO_DATE('05-MAY-25 11:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (34, 1005, 7, TO_DATE('05-MAY-25 11:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (35, 1005, 9, TO_DATE('05-MAY-25 12:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (36, 1004, 2, TO_DATE('05-MAY-25 07:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:00:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (37, 1006, 5, TO_DATE('05-MAY-25 08:10:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:40:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (38, 1007, 3, TO_DATE('05-MAY-25 09:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (39, 1008, 2, TO_DATE('05-MAY-25 09:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (40, 1009, 1, TO_DATE('05-MAY-25 10:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (41, 1010, 3, TO_DATE('05-MAY-25 13:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (42, 1002, 9, TO_DATE('05-MAY-25 14:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (43, 1001, 10, TO_DATE('05-MAY-25 14:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (44, 1006, 8, TO_DATE('05-MAY-25 15:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (45, 1007, 9, TO_DATE('05-MAY-25 15:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (46, 1008, 5, TO_DATE('05-MAY-25 16:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 16:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (47, 1009, 6, TO_DATE('05-MAY-25 16:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 16:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (48, 1010, 7, TO_DATE('05-MAY-25 17:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (49, 1001, 5, TO_DATE('05-MAY-25 17:30:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:55:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (50, 1002, 1, TO_DATE('05-MAY-25 18:00:00', 'DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 18:25:00', 'DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (51, 1015, 11, TO_DATE('05-MAY-25 06:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 06:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (52, 1015, 14, TO_DATE('05-MAY-25 06:30:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 06:55:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (53, 1015, 19, TO_DATE('05-MAY-25 07:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 07:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (54, 1016, 12, TO_DATE('05-MAY-25 08:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (55, 1016, 15, TO_DATE('05-MAY-25 08:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (56, 1016, 20, TO_DATE('05-MAY-25 09:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (57, 1017, 16, TO_DATE('05-MAY-25 10:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:20:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (58, 1017, 13, TO_DATE('05-MAY-25 10:25:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:50:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (59, 1017, 11, TO_DATE('05-MAY-25 10:55:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:20:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (60, 1018, 17, TO_DATE('05-MAY-25 11:30:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:55:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (61, 1018, 12, TO_DATE('05-MAY-25 12:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (62, 1018, 18, TO_DATE('05-MAY-25 12:30:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:55:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (63, 1019, 13, TO_DATE('05-MAY-25 13:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (64, 1019, 15, TO_DATE('05-MAY-25 13:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (65, 1019, 19, TO_DATE('05-MAY-25 14:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (66, 1020, 14, TO_DATE('05-MAY-25 15:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (67, 1020, 16, TO_DATE('05-MAY-25 15:30:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:55:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (68, 1020, 20, TO_DATE('05-MAY-25 16:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 16:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (69, 1015, 13, TO_DATE('05-MAY-25 17:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:20:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (70, 1016, 17, TO_DATE('05-MAY-25 17:25:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:50:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (71, 1017, 18, TO_DATE('05-MAY-25 18:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 18:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (72, 1018, 19, TO_DATE('05-MAY-25 18:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 19:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (73, 1019, 20, TO_DATE('05-MAY-25 19:10:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 19:35:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (74, 1020, 11, TO_DATE('05-MAY-25 19:40:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 20:05:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (75, 1020, 12, TO_DATE('05-MAY-25 20:10:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 20:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (76, 1020, 13, TO_DATE('05-MAY-25 20:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 21:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (77, 1001, 1, TO_DATE('05-MAY-25 06:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 06:25:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (78, 1001, 2, TO_DATE('05-MAY-25 06:30:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 06:55:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (79, 1001, 3, TO_DATE('05-MAY-25 07:00:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 07:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (80, 1002, 4, TO_DATE('05-MAY-25 07:40:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (81, 1002, 5, TO_DATE('05-MAY-25 08:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 08:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (82, 1002, 6, TO_DATE('05-MAY-25 08:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (83, 1003, 7, TO_DATE('05-MAY-25 09:10:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 09:35:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (84, 1003, 8, TO_DATE('05-MAY-25 09:40:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (85, 1003, 9, TO_DATE('05-MAY-25 10:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 10:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (86, 1004, 10, TO_DATE('05-MAY-25 10:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (87, 1004, 1, TO_DATE('05-MAY-25 11:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 11:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (88, 1004, 2, TO_DATE('05-MAY-25 11:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (89, 1015, 3, TO_DATE('05-MAY-25 12:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 12:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (90, 1015, 4, TO_DATE('05-MAY-25 12:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (91, 1015, 5, TO_DATE('05-MAY-25 13:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 13:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (92, 1016, 6, TO_DATE('05-MAY-25 13:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (93, 1016, 7, TO_DATE('05-MAY-25 14:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 14:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (94, 1016, 8, TO_DATE('05-MAY-25 14:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (95, 1017, 9, TO_DATE('05-MAY-25 15:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 15:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (96, 1017, 10, TO_DATE('05-MAY-25 15:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 16:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (97, 1017, 1, TO_DATE('05-MAY-25 16:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 16:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (98, 1018, 2, TO_DATE('05-MAY-25 16:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (99, 1018, 3, TO_DATE('05-MAY-25 17:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 17:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (100, 1018, 4, TO_DATE('05-MAY-25 17:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 18:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (101, 1019, 5, TO_DATE('05-MAY-25 18:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 18:30:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (102, 1019, 6, TO_DATE('05-MAY-25 18:35:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 19:00:00','DD-MON-RR HH24:MI:SS'));
INSERT INTO C##R2KTPS.MEGALL VALUES (103, 1019, 7, TO_DATE('05-MAY-25 19:05:00','DD-MON-RR HH24:MI:SS'), TO_DATE('05-MAY-25 19:30:00','DD-MON-RR HH24:MI:SS'));

REM INSERTING into C##R2KTPS.SZERELVENY
SET DEFINE OFF;
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (222222,1000);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (333333,3000);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (111111,2000);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (444444,1000);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (555555,1500);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (102345,320);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (112367,280);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (123456,150);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (134579,340);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (145321,400);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (156789,250);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (167890,310);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (178901,290);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (189012,370);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (190123,160);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (201234,210);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (212345,260);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (223456,330);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (234567,300);
Insert into C##R2KTPS.SZERELVENY (MOZDONYSZAM,KAPACITAS) values (245678,190);
REM INSERTING into C##R2KTPS.TAG
SET DEFINE OFF;
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('jozan.mihaly1022@ez.hu','SzuperTitkosJelszo001!','Józan Mihály');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('nagy.eva@gmail.com','SzuperTitkosJelszo002!','Nagy Éva');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('szabo.peter@gmail.com','SzuperTitkosJelszo003!','Szabó Péter');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('kovacs.anna@gmail.com','SzuperTitkosJelszo004!','Kovács Anna');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('toth.istvan@gmail.com','SzuperTitkosJelszo005!','Tóth István');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('horvath.maria@gmail.com','SzuperTitkosJelszo006!','Horváth Mária');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('valaki@valami.hu','$2y$10$/uqGkWoD5/SKB9N/HpGvNuq/anGcFUac5gKX2LP8N6jdv7cG1RIM2','Valaki');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('varga.katalin@gmail.com','SzuperTitkosJelszo008!','Varga Katalin');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('balogh.gabor@gmail.com','SzuperTitkosJelszo009!','Balogh Gábor');
Insert into C##R2KTPS.TAG (EMAIL,JELSZO,NEV) values ('ez','$2y$10$F5ArhSE7nUMwALNKOvSsz.WopqN1UPOlqJRAWz0Vd1h4aHc3iltny','az');
REM INSERTING into C##R2KTPS.VASARLAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."ADMIN_PK" ON "C##R2KTPS"."ADMIN" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."ALLOMAS_PK" ON "C##R2KTPS"."ALLOMAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JARAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."JARAT_PK" ON "C##R2KTPS"."JARAT" ("JARATSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JEGY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."JEGY_PK" ON "C##R2KTPS"."JEGY" ("AZONOSITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEGALL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."MEGALL_PK" ON "C##R2KTPS"."MEGALL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."SZERELVENY_PK" ON "C##R2KTPS"."SZERELVENY" ("MOZDONYSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."TAG_PK" ON "C##R2KTPS"."TAG" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VASARLAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##R2KTPS"."VASARLAS_PK" ON "C##R2KTPS"."VASARLAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADMIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."ADMIN_TRG" 
BEFORE INSERT ON ADMIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMIN_ID IS NULL THEN
      SELECT ADMIN_SEQ.NEXTVAL INTO :NEW.ADMIN_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."ADMIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."ALLOMAS_TRG" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."ALLOMAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."ALLOMAS_TRG1" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."ALLOMAS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ALLOMAS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."ALLOMAS_TRG2" 
BEFORE INSERT ON ALLOMAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ALLOMAS_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."ALLOMAS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JARAT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."JARAT_TRG" 
BEFORE INSERT ON JARAT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.JARATSZAM IS NULL THEN
      SELECT JARAT_SEQ.NEXTVAL INTO :NEW.JARATSZAM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."JARAT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JEGY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."JEGY_TRG" 
BEFORE INSERT ON JEGY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."JEGY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KEDVEZMENY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."KEDVEZMENY_TRG" 
BEFORE INSERT ON KEDVEZMENY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT KEDVEZMENY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."KEDVEZMENY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEGALLO_IDO_CHECKER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."MEGALLO_IDO_CHECKER_TRG" 
BEFORE INSERT OR UPDATE ON MEGALL
FOR EACH ROW
BEGIN
IF :NEW.ERKEZES IS NOT NULL AND :NEW.INDULAS IS NOT NULL AND
:NEW.ERKEZES >
:NEW.INDULAS THEN
RAISE_APPLICATION_ERROR(-20001, 'Az érkezési idő nem lehet későbbi az
indulásnál.');
END IF;
END;
/
ALTER TRIGGER "C##R2KTPS"."MEGALLO_IDO_CHECKER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEGALLO_NEV_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."MEGALLO_NEV_TRG" 
BEFORE INSERT OR UPDATE ON ALLOMAS
FOR EACH ROW
BEGIN
IF :NEW.NEV IS NOT NULL THEN
:NEW.NEV := UPPER(SUBSTR(:NEW.NEV, 1, 1)) || LOWER(SUBSTR(:NEW.NEV, 2));
END IF;
END;
/
ALTER TRIGGER "C##R2KTPS"."MEGALLO_NEV_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEGALL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."MEGALL_TRG" 
BEFORE INSERT ON MEGALL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MEGALL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."MEGALL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_VASARLAS_DATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."SET_VASARLAS_DATE" 
BEFORE INSERT ON VASARLAS
FOR EACH ROW
BEGIN
    :NEW.DATUM := SYSDATE;
END;



/
ALTER TRIGGER "C##R2KTPS"."SET_VASARLAS_DATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SZERELVENY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."SZERELVENY_TRG" 
BEFORE INSERT ON SZERELVENY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "C##R2KTPS"."SZERELVENY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UNIQUE_TAG_EMAIL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##R2KTPS"."UNIQUE_TAG_EMAIL" 
BEFORE INSERT ON TAG
FOR EACH ROW
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM ADMIN WHERE email = :NEW.email;
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ez az email már foglalt egy adminnál.');
    END IF;
END;



/
ALTER TRIGGER "C##R2KTPS"."UNIQUE_TAG_EMAIL" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_TAG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##R2KTPS"."ADD_TAG" (
    n_email IN VARCHAR2,
    n_pswrd IN VARCHAR2,
    n_name IN VARCHAR2
) AS
BEGIN
    INSERT INTO TAG (EMAIL, JELSZO, NEV)
    VALUES (n_email, n_pswrd, n_name);
END;



/
--------------------------------------------------------
--  DDL for Procedure GET_NEXT_VASARLAS_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##R2KTPS"."GET_NEXT_VASARLAS_ID" (
    p_next_id OUT NUMBER
)
AS
BEGIN
    SELECT NVL(MAX(ID), 0) + 1 INTO p_next_id
    FROM VASARLAS;
END;



/
--------------------------------------------------------
--  DDL for Procedure SZEMELY_KKIR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##R2KTPS"."SZEMELY_KKIR" (p_szigsz IN Szemelyek.szigsz%TYPE)
IS
    -- Lokális deklaráció
    v_szemely Szemelyek%ROWTYPE;
BEGIN
    SELECT * INTO v_szemely FROM Szemelyek WHERE szigsz = p_szigsz;
    DBMS_OUTPUT.PUT_LINE('A személy személyigazolványszáma: ' ||
    v_szemely.szigsz || ', neve: ' || v_szemely.nev || ', születési dátuma ' ||
    TO_CHAR(v_szemely.szuletesiDatum,'YYYY.MM.DD') || ', irányítószáma: ' ||
    v_szemely.irsz || ', országa: ' || v_szemely.orszag ||
    ', hallgatói státusza: ' || v_szemely.hallgatoE || ' .');
END;

-- Külön PL/SQL blokk
SET SERVEROUTPUT ON
BEGIN
    -- Eljárás hívása
    szemely_kkir('840388SD');
END;


/
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."ALLOMAS" ADD CONSTRAINT "ALLOMAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."ALLOMAS" MODIFY ("HELY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JARAT
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JARAT" ADD CONSTRAINT "JARAT_PK" PRIMARY KEY ("JARATSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."JARAT" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JARAT" MODIFY ("SZERELVENY_MOZDONYSZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KEDVEZMENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."KEDVEZMENY" MODIFY ("MERTEKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VASARLAS
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."VASARLAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."VASARLAS" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."VASARLAS" MODIFY ("FIZETESI_MOD" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."VASARLAS" ADD CONSTRAINT "VASARLAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEGALL
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."MEGALL" ADD CONSTRAINT "MEGALL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."MEGALL" MODIFY ("ALLOMAS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_PK" PRIMARY KEY ("AZONOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("AZONOSITO" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("JARAT_JARATSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("VASARLAS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("ERVENYESSEG" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("JEGYAR" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("KEDVEZMENYEK_ID" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."JEGY" MODIFY ("TAG_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("MOZDONYSZAM" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" MODIFY ("KAPACITAS" NOT NULL ENABLE);
  ALTER TABLE "C##R2KTPS"."SZERELVENY" ADD CONSTRAINT "SZERELVENY_PK" PRIMARY KEY ("MOZDONYSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_FK_JARAT" FOREIGN KEY ("JARAT_JARATSZAM")
	  REFERENCES "C##R2KTPS"."JARAT" ("JARATSZAM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_FK_TAG_EMAIL" FOREIGN KEY ("TAG_EMAIL")
	  REFERENCES "C##R2KTPS"."TAG" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##R2KTPS"."JEGY" ADD CONSTRAINT "JEGY_FK_VASARLAS" FOREIGN KEY ("VASARLAS_ID")
	  REFERENCES "C##R2KTPS"."VASARLAS" ("ID") ON DELETE CASCADE ENABLE;
